"""Player Tactical DNA — radar chart of composite tactical dimensions."""
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from src.data.duckdb_loader import connect, list_match_ids

DATA_ROOT = Path(__file__).resolve().parents[1] / "data"
DB_PATH = DATA_ROOT / "skillcorner.duckdb"

DIMENSIONS = [
    "Run Threat",
    "Space Creation",
    "Def. Disruption",
    "Ball Carrying",
    "Passing Quality",
    "Press Intensity",
]

DIMENSION_DESCRIPTIONS = {
    "Run Threat": "xT generated by off-ball runs × targeting rate bonus",
    "Space Creation": "Open-space receptions + forward momentum count",
    "Def. Disruption": "Direct disruptions, stopped dangers, forced backward passes",
    "Ball Carrying": "Long carries (8m+) weighted by speed",
    "Passing Quality": "Pass accuracy volume + one-touch plays + dangerous completions",
    "Press Intensity": "Pressing volume + pressing chain involvement + high-speed engagements",
}

PLAYER_COLORS = ["#1E88E5", "#E53935", "#43A047", "#FB8C00", "#8E24AA"]

GK_POSITIONS = {"GK"}


@st.cache_data(ttl=300)
def compute_all_player_scores(_conn_key: str, match_ids: tuple) -> pd.DataFrame:
    """Compute tactical DNA scores for every player across the given matches."""
    conn = connect(DB_PATH, read_only=True)
    placeholders = ",".join(["?"] * len(match_ids))
    df = conn.execute(
        f"SELECT * FROM dynamic_events WHERE match_id IN ({placeholders})",
        list(match_ids),
    ).df()

    bool_cols = [
        "targeted", "received", "dangerous", "difficult_pass_target",
        "forward_momentum", "carry", "one_touch", "pressing_chain",
        "stop_possession_danger", "force_backward", "beaten_by_possession",
    ]
    for col in bool_cols:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip().str.lower().map(
                {"true": True, "false": False, "1": True, "0": False}
            )

    records = []
    for (pid, pname, pos, tid, tname), g in df.groupby(
        ["player_id", "player_name", "player_position", "team_id", "team_shortname"]
    ):
        if pos in GK_POSITIONS:
            continue

        runs = g[g["event_type"] == "off_ball_run"]
        poss = g[g["event_type"] == "player_possession"]
        eng = g[g["event_type"] == "on_ball_engagement"]

        # ── 1. Run Threat ──────────────────────────────────────────────────────
        run_xthreat = pd.to_numeric(runs["xthreat"], errors="coerce").sum()
        n_runs = len(runs)
        targeted_rate = (runs["targeted"] == True).mean() if n_runs > 0 else 0
        run_threat = float(run_xthreat * (1.0 + targeted_rate))

        # ── 2. Space Creation ──────────────────────────────────────────────────
        sep_start = pd.to_numeric(poss["separation_start"], errors="coerce")
        open_receptions = int((sep_start >= 6).sum())
        fwd_mom = int((poss["forward_momentum"] == True).sum())
        space_creation = float(open_receptions + fwd_mom * 0.6)

        # ── 3. Defensive Disruption ────────────────────────────────────────────
        direct_disruptions = int((eng["end_type"] == "direct_disruption").sum())
        direct_regains = int((eng["end_type"] == "direct_regain").sum())
        stop_danger = int((g["stop_possession_danger"] == True).sum())
        force_bwd = int((g["force_backward"] == True).sum())
        def_disruption = float(direct_disruptions * 2 + direct_regains + stop_danger + force_bwd * 0.5)

        # ── 4. Ball Carrying ───────────────────────────────────────────────────
        carries = poss[poss["carry"] == True]
        dist = pd.to_numeric(carries["distance_covered"], errors="coerce")
        speed = pd.to_numeric(carries["speed_avg"], errors="coerce")
        long_carries = int((dist >= 8).sum())
        fast_long_carries = int(((dist >= 8) & (speed >= 15)).sum())
        ball_carrying = float(long_carries + fast_long_carries * 1.5)

        # ── 5. Passing Quality ─────────────────────────────────────────────────
        all_passes = poss[poss["pass_outcome"].notna() & (poss["pass_outcome"] != "")]
        n_passes = len(all_passes)
        n_successful = int((all_passes["pass_outcome"] == "successful").sum())
        accuracy = n_successful / n_passes if n_passes > 0 else 0
        one_touch = int(
            ((poss["one_touch"] == True) & (poss["end_type"] == "pass")).sum()
        )
        # dangerous completions from possession: targeted=True, received=True, dangerous=True
        dangerous_comp = int(
            ((runs["targeted"] == True) & (runs["received"] == True) & (runs["dangerous"] == True)).sum()
        )
        passing_quality = float(accuracy * n_passes * 0.25 + one_touch + dangerous_comp * 2)

        # ── 6. Press Intensity ─────────────────────────────────────────────────
        pressing = eng[eng["event_subtype"] == "pressing"]
        chain_involvement = int((g["pressing_chain"] == True).sum())
        high_speed_press = int(
            (pd.to_numeric(pressing["speed_avg"], errors="coerce") >= 20).sum()
        )
        press_intensity = float(len(pressing) + chain_involvement * 0.4 + high_speed_press * 1.5)

        records.append(
            {
                "player_id": pid,
                "player_name": pname,
                "player_position": pos,
                "team_id": tid,
                "team_name": tname,
                "run_threat": run_threat,
                "space_creation": space_creation,
                "def_disruption": def_disruption,
                "ball_carrying": ball_carrying,
                "passing_quality": passing_quality,
                "press_intensity": press_intensity,
            }
        )

    result = pd.DataFrame(records)
    if result.empty:
        return result

    raw_dims = ["run_threat", "space_creation", "def_disruption", "ball_carrying", "passing_quality", "press_intensity"]
    for dim in raw_dims:
        result[f"{dim}_pct"] = result[dim].rank(pct=True) * 100

    return result


def radar_trace(values: list[float], name: str, color: str) -> go.Scatterpolar:
    closed = values + [values[0]]
    closed_labels = DIMENSIONS + [DIMENSIONS[0]]
    rgba = f"rgba{tuple(int(color.lstrip('#')[i:i+2], 16) for i in (0,2,4)) + (0.22,)}"
    return go.Scatterpolar(
        r=closed,
        theta=closed_labels,
        fill="toself",
        name=name,
        line=dict(color=color, width=2.5),
        fillcolor=rgba,
        hovertemplate="<b>%{theta}</b><br>Percentile: %{r:.0f}<extra>" + name + "</extra>",
    )


def build_radar(players_df: pd.DataFrame) -> go.Figure:
    raw_dims = ["run_threat", "space_creation", "def_disruption", "ball_carrying", "passing_quality", "press_intensity"]
    fig = go.Figure()

    for i, (_, row) in enumerate(players_df.iterrows()):
        values = [round(row[f"{d}_pct"], 1) for d in raw_dims]
        color = PLAYER_COLORS[i % len(PLAYER_COLORS)]
        fig.add_trace(radar_trace(values, row["player_name"], color))

    fig.update_layout(
        polar=dict(
            radialaxis=dict(
                visible=True,
                range=[0, 100],
                ticksuffix="th",
                tickvals=[25, 50, 75, 100],
                tickfont=dict(size=10),
                gridcolor="rgba(150,150,150,0.3)",
            ),
            angularaxis=dict(tickfont=dict(size=12)),
            bgcolor="rgba(0,0,0,0)",
        ),
        showlegend=True,
        legend=dict(orientation="h", yanchor="bottom", y=-0.18, xanchor="center", x=0.5),
        height=520,
        margin=dict(l=60, r=60, t=40, b=80),
        paper_bgcolor="rgba(0,0,0,0)",
    )
    return fig


def main() -> None:
    st.title("🧬 Player Tactical DNA")
    st.write(
        "Six composite dimensions computed from tracking data and ranked as percentiles "
        "across all players in the selected data. Compare up to **5 players** side by side."
    )

    conn = connect(DB_PATH, read_only=True)
    all_match_ids = list_match_ids(conn)
    if not all_match_ids:
        st.warning("No matches found. Build the database first.")
        return

    # ── Scope & match selection ────────────────────────────────────────────────
    col_scope, col_match = st.columns([1, 2])
    with col_scope:
        scope = st.radio("Normalise against", ["Single match", "All matches"])
    with col_match:
        if scope == "Single match":
            selected_match = st.selectbox("Match", all_match_ids)
            match_ids_for_norm = (selected_match,)
        else:
            selected_match = st.selectbox("Browse match", all_match_ids)
            match_ids_for_norm = tuple(all_match_ids)
            st.caption(f"Percentiles computed across all {len(all_match_ids)} matches")

    with st.spinner("Computing tactical scores…"):
        all_scores = compute_all_player_scores(str(DB_PATH), match_ids_for_norm)

    if all_scores.empty:
        st.warning("Not enough data to compute scores.")
        return

    # Filter to current match for player selection
    match_scores = all_scores[all_scores["team_id"].isin(
        conn.execute(
            "SELECT DISTINCT team_id FROM dynamic_events WHERE match_id = ?",
            [selected_match],
        ).df()["team_id"].tolist()
    )]

    # ── Player selection ───────────────────────────────────────────────────────
    st.subheader("Select players to compare")

    team_names = sorted(match_scores["team_name"].unique().tolist())
    col_t1, col_t2 = st.columns(2)
    with col_t1:
        team_a = st.selectbox("Team A", team_names, index=0)
    with col_t2:
        team_b = st.selectbox("Team B", team_names, index=min(1, len(team_names) - 1))

    def player_options(team: str) -> dict:
        sub = match_scores[match_scores["team_name"] == team].sort_values("player_name")
        return {
            f"{r['player_name']} ({r['player_position']})": r["player_id"]
            for _, r in sub.iterrows()
        }

    opts_a = player_options(team_a)
    opts_b = player_options(team_b)

    col_pa, col_pb = st.columns(2)
    with col_pa:
        selected_a = st.multiselect(
            f"{team_a} players", list(opts_a.keys()),
            default=list(opts_a.keys())[:1], max_selections=3,
        )
    with col_pb:
        selected_b = st.multiselect(
            f"{team_b} players", list(opts_b.keys()),
            default=list(opts_b.keys())[:1], max_selections=2,
        )

    selected_ids = (
        [opts_a[n] for n in selected_a] + [opts_b[n] for n in selected_b]
    )
    if not selected_ids:
        st.info("Select at least one player.")
        return

    players_df = all_scores[all_scores["player_id"].isin(selected_ids)].copy()
    # Preserve selection order
    order = {pid: i for i, pid in enumerate(selected_ids)}
    players_df = players_df.sort_values("player_id", key=lambda s: s.map(order))

    # ── Radar chart ────────────────────────────────────────────────────────────
    st.plotly_chart(build_radar(players_df), use_container_width=True)

    # ── Dimension legend ───────────────────────────────────────────────────────
    with st.expander("What does each dimension measure?"):
        for dim, desc in DIMENSION_DESCRIPTIONS.items():
            st.markdown(f"**{dim}** — {desc}")

    # ── Score table ────────────────────────────────────────────────────────────
    st.subheader("Percentile scores")
    raw_dims = ["run_threat", "space_creation", "def_disruption", "ball_carrying", "passing_quality", "press_intensity"]
    display_cols = {f"{d}_pct": label for d, label in zip(raw_dims, DIMENSIONS)}

    table = players_df[["player_name", "player_position", "team_name"] + list(display_cols.keys())].copy()
    table = table.rename(columns={**display_cols, "player_name": "Player", "player_position": "Pos", "team_name": "Team"})

    for col in DIMENSIONS:
        table[col] = table[col].round(1)

    st.dataframe(
        table.set_index("Player"),
        use_container_width=True,
        column_config={dim: st.column_config.ProgressColumn(dim, min_value=0, max_value=100, format="%.0f") for dim in DIMENSIONS},
    )

    # ── League context bar ─────────────────────────────────────────────────────
    st.subheader("How rare is each dimension?")
    st.caption("Distribution of each dimension across all players in scope — selected players shown as markers.")

    raw_dims_map = dict(zip(raw_dims, DIMENSIONS))
    dim_col = st.selectbox("Dimension", DIMENSIONS)
    raw_col = [k for k, v in raw_dims_map.items() if v == dim_col][0] + "_pct"

    hist_data = all_scores[raw_col].dropna()
    selected_vals = players_df[raw_col].tolist()
    selected_names = players_df["player_name"].tolist()

    fig_hist = go.Figure()
    fig_hist.add_trace(go.Histogram(
        x=hist_data, nbinsx=20,
        marker_color="rgba(100,150,220,0.55)",
        name="All players",
        hovertemplate="Percentile range: %{x}<br>Count: %{y}<extra></extra>",
    ))
    for val, name, color in zip(selected_vals, selected_names, PLAYER_COLORS):
        fig_hist.add_vline(
            x=val, line_dash="dash", line_color=color,
            annotation_text=name.split()[-1], annotation_position="top",
        )
    fig_hist.update_layout(
        xaxis_title="Percentile",
        yaxis_title="# Players",
        height=300,
        margin=dict(l=20, r=20, t=20, b=40),
        showlegend=False,
    )
    st.plotly_chart(fig_hist, use_container_width=True)


if __name__ == "__main__":
    main()
